# 서버 설정
server:
  port: 4040

spring:
  application:
    name: oauth

# 데이터 소스 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: poceania1358@gmail.com
    password: aiin iwhz zekw dten
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Kakao OAuth2.0
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 56e33c5b2970077ec9a76e3ef08d7149
            client-secret: rVYeXWXptEuzRb8qnlHjSWsnvO0IDoRG
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname

          naver:
            client-id: HJB54J6UiNJMZvvLfvam
            client-secret: OjsvDtNWDX
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email

# Kakao OAuth2 Provider
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id

# JWT Secret Key
secret-key: thisissecretkeyoauthtestexamplestudy